# Generated by Django 2.1.15 on 2020-03-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='system_object',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('object_type', models.IntegerField()),
                ('object_name', models.CharField(max_length=64)),
                ('operation_code', models.CharField(max_length=32, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('belong_to', models.IntegerField(null=True)),
            ],
        ),
    ]
