# Generated by Django 2.1.15 on 2020-03-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.IntegerField()),
                ('object_name', models.CharField(max_length=64)),
                ('operation_code', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('belong_to', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'system_object',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SystemRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'system_role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SystemRoleRight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.IntegerField()),
                ('sysobjectid', models.IntegerField()),
                ('operation', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'system_role_right',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SystemUserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'system_user_role',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='system_object',
        ),
    ]
