# Generated by Django 2.1.15 on 2020-03-05 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20200305_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemrole',
            options={},
        ),
    ]
