# Generated by Django 2.1.15 on 2020-01-10 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginserver', '0003_auto_20200110_0454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='average_user',
            name='birthday',
        ),
    ]
