# Generated by Django 2.1.15 on 2020-01-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginserver', '0004_remove_average_user_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='average_user',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
